// GENERATED by scripts/generate-scaffold.mjs — do not edit page mappings by hand.
// Runtime route manifest / sitemap: the single source of truth for navigation
// and V1 coverage tracking (PROJECT_CONTEXT.md §9). Re-run the generator after
// editing the route table there.

export type Role =
  | "public"
  | "referring"
  | "receiving"
  | "coordinator"
  | "caseManager"
  | "admin";

export type Tier = "must" | "should" | "nice";

export type RouteGroup =
  | "public"
  | "auth"
  | "account"
  | "referring"
  | "receiving"
  | "admin"
  | "system";

export interface RouteMeta {
  /** Stable identifier used by <PlaceholderPage routeId="..." />. */
  id: string;
  /** Page name from §9. */
  title: string;
  /** §9 sub-section, e.g. "9A". */
  section: string;
  group: RouteGroup;
  /** URL path relative to /[locale] ("*" for special files). */
  path: string;
  /** page file relative to app/[locale]. */
  file: string;
  tier: Tier;
  /** RBAC roles allowed to see this page. */
  roles: Role[];
  /** Section 14 acceptance-test scenario numbers this page maps to. */
  tests?: number[];
  /** Rendered via a Next special file (not-found.tsx / error.tsx). */
  special?: boolean;
  note?: string;
}

export const ROLE_LABELS: Record<Role, string> = {
  public: "Public / unauthenticated",
  referring: "Referring clinician",
  receiving: "Receiving clinician",
  coordinator: "Hospital coordinator",
  caseManager: "LibaMed case manager",
  admin: "Compliance / admin",
};

export const TIER_LABELS: Record<Tier, string> = {
  must: "Must Have (V1)",
  should: "Should Have (V1.5)",
  nice: "Nice to Have (V2+)",
};

export const GROUP_LABELS: Record<RouteGroup, string> = {
  public: "Public site",
  auth: "Auth & account",
  account: "Account",
  referring: "Referring clinician portal",
  receiving: "Receiving / hospital portal",
  admin: "LibaMed admin / governance",
  system: "System / state",
};

export const ROUTES: RouteMeta[] = [
  {
    "id": "public.home",
    "title": "Home / landing",
    "section": "9A",
    "group": "public",
    "path": "/",
    "file": "(public)/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.how-it-works",
    "title": "How it works",
    "section": "9A",
    "group": "public",
    "path": "/how-it-works",
    "file": "(public)/how-it-works/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.pledge",
    "title": "The LibaMed Pledge",
    "section": "9A",
    "group": "public",
    "path": "/pledge",
    "file": "(public)/pledge/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.specialties",
    "title": "Specialties directory",
    "section": "9A",
    "group": "public",
    "path": "/specialties",
    "file": "(public)/specialties/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.hospitals",
    "title": "Partner hospitals list",
    "section": "9A",
    "group": "public",
    "path": "/hospitals",
    "file": "(public)/hospitals/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.hospital-profile",
    "title": "Hospital profile (data-driven template)",
    "section": "9A",
    "group": "public",
    "path": "/hospitals/[hospitalId]",
    "file": "(public)/hospitals/[hospitalId]/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.for-clinicians",
    "title": "For clinicians (info + register entry)",
    "section": "9A",
    "group": "public",
    "path": "/for-clinicians",
    "file": "(public)/for-clinicians/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.contact",
    "title": "Contact",
    "section": "9A",
    "group": "public",
    "path": "/contact",
    "file": "(public)/contact/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.faq",
    "title": "FAQ + glossary",
    "section": "9A",
    "group": "public",
    "path": "/faq",
    "file": "(public)/faq/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.privacy",
    "title": "Privacy policy",
    "section": "9A",
    "group": "public",
    "path": "/legal/privacy",
    "file": "(public)/legal/privacy/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.cookies",
    "title": "Cookie policy (+ consent banner)",
    "section": "9A",
    "group": "public",
    "path": "/legal/cookies",
    "file": "(public)/legal/cookies/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.terms",
    "title": "Terms of service",
    "section": "9A",
    "group": "public",
    "path": "/legal/terms",
    "file": "(public)/legal/terms/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.acceptable-use",
    "title": "Acceptable use policy",
    "section": "9A",
    "group": "public",
    "path": "/legal/acceptable-use",
    "file": "(public)/legal/acceptable-use/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.accessibility",
    "title": "Accessibility statement",
    "section": "9A",
    "group": "public",
    "path": "/legal/accessibility",
    "file": "(public)/legal/accessibility/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "note": "WCAG 2.2 AA is the floor (§8.4)."
  },
  {
    "id": "public.security",
    "title": "Security / trust page",
    "section": "9A",
    "group": "public",
    "path": "/security",
    "file": "(public)/security/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "public.sub-processors",
    "title": "Data processing / sub-processors",
    "section": "9A",
    "group": "public",
    "path": "/legal/sub-processors",
    "file": "(public)/legal/sub-processors/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.register",
    "title": "Register",
    "section": "9B",
    "group": "auth",
    "path": "/register",
    "file": "(auth)/register/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "tests": [
      1
    ]
  },
  {
    "id": "auth.gmc-verification",
    "title": "GMC verification step",
    "section": "9B",
    "group": "auth",
    "path": "/register/gmc-verification",
    "file": "(auth)/register/gmc-verification/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "tests": [
      1
    ],
    "note": "OPEN QUESTION (§6.1): confirm GMC verification method — no obvious public GMC API. Gates the entire referring-clinician flow."
  },
  {
    "id": "auth.login",
    "title": "Login",
    "section": "9B",
    "group": "auth",
    "path": "/login",
    "file": "(auth)/login/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.mfa-enrolment",
    "title": "MFA enrolment",
    "section": "9B",
    "group": "auth",
    "path": "/mfa/enrolment",
    "file": "(auth)/mfa/enrolment/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "note": "MFA required for all clinician + admin accounts (§7.4)."
  },
  {
    "id": "auth.mfa-challenge",
    "title": "MFA challenge",
    "section": "9B",
    "group": "auth",
    "path": "/mfa/challenge",
    "file": "(auth)/mfa/challenge/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.forgot-password",
    "title": "Forgot password",
    "section": "9B",
    "group": "auth",
    "path": "/forgot-password",
    "file": "(auth)/forgot-password/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.reset-password",
    "title": "Reset password",
    "section": "9B",
    "group": "auth",
    "path": "/reset-password",
    "file": "(auth)/reset-password/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.verify-email",
    "title": "Email verification",
    "section": "9B",
    "group": "auth",
    "path": "/verify-email",
    "file": "(auth)/verify-email/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "auth.account-pending",
    "title": "Account pending / under review",
    "section": "9B",
    "group": "auth",
    "path": "/account-pending",
    "file": "(auth)/account-pending/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "account.profile",
    "title": "Profile & settings",
    "section": "9B",
    "group": "account",
    "path": "/account",
    "file": "(app)/account/page.tsx",
    "tier": "must",
    "roles": [
      "referring",
      "receiving",
      "coordinator",
      "caseManager",
      "admin"
    ]
  },
  {
    "id": "account.sessions",
    "title": "Session & device management (view + revoke)",
    "section": "9B",
    "group": "account",
    "path": "/account/sessions",
    "file": "(app)/account/sessions/page.tsx",
    "tier": "must",
    "roles": [
      "referring",
      "receiving",
      "coordinator",
      "caseManager",
      "admin"
    ],
    "note": "Users can see and revoke active sessions (§7.4)."
  },
  {
    "id": "account.notifications",
    "title": "Notification preferences",
    "section": "9B",
    "group": "account",
    "path": "/account/notifications",
    "file": "(app)/account/notifications/page.tsx",
    "tier": "should",
    "roles": [
      "referring",
      "receiving",
      "coordinator",
      "caseManager",
      "admin"
    ],
    "note": "Notifications are Should-Have / V1.5 (§8.5). Shell scaffolded now; preferences only."
  },
  {
    "id": "referring.dashboard",
    "title": "Dashboard (all cases, filterable)",
    "section": "9C",
    "group": "referring",
    "path": "/referring",
    "file": "(app)/referring/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2
    ]
  },
  {
    "id": "referring.intake.patient",
    "title": "Intake wizard — step 1: patient details",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/patient",
    "file": "(app)/referring/intake/patient/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2
    ]
  },
  {
    "id": "referring.intake.clinical",
    "title": "Intake wizard — step 2: clinical summary",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/clinical",
    "file": "(app)/referring/intake/clinical/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2
    ]
  },
  {
    "id": "referring.intake.corridor",
    "title": "Intake wizard — step 3: corridor + specialty",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/corridor",
    "file": "(app)/referring/intake/corridor/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2,
      4
    ],
    "note": "Selecting the corridor sets the case data-residency region automatically (§2.1/§7.1)."
  },
  {
    "id": "referring.intake.documents",
    "title": "Intake wizard — step 4: document / DICOM upload",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/documents",
    "file": "(app)/referring/intake/documents/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      3
    ],
    "note": "Large/DICOM uploads go direct to object storage via presigned, resumable URLs (§2.5). No DICOM viewer in V1."
  },
  {
    "id": "referring.intake.consent",
    "title": "Intake wizard — step 5: itemised consent",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/consent",
    "file": "(app)/referring/intake/consent/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2,
      7
    ],
    "note": "Itemised, versioned, immutable consent — not a checkbox (§7.3)."
  },
  {
    "id": "referring.intake.review",
    "title": "Intake wizard — step 6: review & submit",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/review",
    "file": "(app)/referring/intake/review/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2
    ]
  },
  {
    "id": "referring.case-created",
    "title": "Case created confirmation",
    "section": "9C",
    "group": "referring",
    "path": "/referring/intake/confirmation",
    "file": "(app)/referring/intake/confirmation/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      2
    ]
  },
  {
    "id": "referring.case-detail",
    "title": "Case detail (status tracker + documents)",
    "section": "9C",
    "group": "referring",
    "path": "/referring/cases/[caseId]",
    "file": "(app)/referring/cases/[caseId]/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      3,
      4
    ]
  },
  {
    "id": "referring.messages",
    "title": "Secure messaging thread",
    "section": "9C",
    "group": "referring",
    "path": "/referring/cases/[caseId]/messages",
    "file": "(app)/referring/cases/[caseId]/messages/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      6
    ]
  },
  {
    "id": "referring.treatment-plan",
    "title": "Treatment plan received view",
    "section": "9C",
    "group": "referring",
    "path": "/referring/cases/[caseId]/treatment-plan",
    "file": "(app)/referring/cases/[caseId]/treatment-plan/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      5
    ]
  },
  {
    "id": "referring.consent",
    "title": "Consent view + withdrawal flow",
    "section": "9C",
    "group": "referring",
    "path": "/referring/cases/[caseId]/consent",
    "file": "(app)/referring/cases/[caseId]/consent/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      7
    ],
    "note": "Withdrawal triggers the defined stop-processing workflow, logged immutably (§7.3)."
  },
  {
    "id": "referring.summary",
    "title": "Clinical summary handback view",
    "section": "9C",
    "group": "referring",
    "path": "/referring/cases/[caseId]/summary",
    "file": "(app)/referring/cases/[caseId]/summary/page.tsx",
    "tier": "must",
    "roles": [
      "referring"
    ],
    "tests": [
      8
    ]
  },
  {
    "id": "receiving.queue",
    "title": "Incoming case queue (named specialist, never shared inbox)",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving",
    "file": "(app)/receiving/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      4
    ],
    "note": "Cases route to a NAMED specialist queue — never a shared inbox (§8.2)."
  },
  {
    "id": "receiving.case-detail",
    "title": "Case detail + document access",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]",
    "file": "(app)/receiving/cases/[caseId]/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      3
    ]
  },
  {
    "id": "receiving.dicom",
    "title": "DICOM download view",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]/dicom",
    "file": "(app)/receiving/cases/[caseId]/dicom/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      3
    ],
    "note": "V1 = secure DICOM download/upload only; viewer deferred to V2 (§2.5)."
  },
  {
    "id": "receiving.treatment-plan",
    "title": "Treatment plan response template",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]/treatment-plan",
    "file": "(app)/receiving/cases/[caseId]/treatment-plan/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      5
    ]
  },
  {
    "id": "receiving.request-info",
    "title": "Request additional information",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]/request-info",
    "file": "(app)/receiving/cases/[caseId]/request-info/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ]
  },
  {
    "id": "receiving.messages",
    "title": "Messaging thread (receiving side)",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]/messages",
    "file": "(app)/receiving/cases/[caseId]/messages/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      6
    ]
  },
  {
    "id": "receiving.summary",
    "title": "Submit clinical summary form",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/cases/[caseId]/summary",
    "file": "(app)/receiving/cases/[caseId]/summary/page.tsx",
    "tier": "must",
    "roles": [
      "receiving"
    ],
    "tests": [
      8
    ]
  },
  {
    "id": "receiving.coordinator",
    "title": "Hospital coordinator dashboard",
    "section": "9D",
    "group": "receiving",
    "path": "/receiving/coordinator",
    "file": "(app)/receiving/coordinator/page.tsx",
    "tier": "must",
    "roles": [
      "coordinator"
    ]
  },
  {
    "id": "admin.dashboard",
    "title": "Admin dashboard (case flow across corridors)",
    "section": "9E",
    "group": "admin",
    "path": "/admin",
    "file": "(app)/admin/page.tsx",
    "tier": "must",
    "roles": [
      "admin",
      "caseManager"
    ]
  },
  {
    "id": "admin.case-detail",
    "title": "Case oversight detail",
    "section": "9E",
    "group": "admin",
    "path": "/admin/cases/[caseId]",
    "file": "(app)/admin/cases/[caseId]/page.tsx",
    "tier": "must",
    "roles": [
      "admin",
      "caseManager"
    ]
  },
  {
    "id": "admin.hospitals",
    "title": "Partner hospital list",
    "section": "9E",
    "group": "admin",
    "path": "/admin/hospitals",
    "file": "(app)/admin/hospitals/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ]
  },
  {
    "id": "admin.hospital-edit",
    "title": "Partner hospital add/edit",
    "section": "9E",
    "group": "admin",
    "path": "/admin/hospitals/[hospitalId]/edit",
    "file": "(app)/admin/hospitals/[hospitalId]/edit/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ],
    "note": "Add + edit share this shell. Partner-hospital data must be admin-editable without a developer (§8.3)."
  },
  {
    "id": "admin.clinicians",
    "title": "Named clinician management",
    "section": "9E",
    "group": "admin",
    "path": "/admin/clinicians",
    "file": "(app)/admin/clinicians/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ]
  },
  {
    "id": "admin.corridors",
    "title": "Corridor configuration",
    "section": "9E",
    "group": "admin",
    "path": "/admin/corridors",
    "file": "(app)/admin/corridors/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ],
    "note": "Corridor is a first-class config object (§4/§10): residency, transfer mechanism, consent wording, retention, language pack, partner directory."
  },
  {
    "id": "admin.users",
    "title": "User & role management (RBAC)",
    "section": "9E",
    "group": "admin",
    "path": "/admin/users",
    "file": "(app)/admin/users/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ]
  },
  {
    "id": "admin.audit",
    "title": "Audit log viewer + export",
    "section": "9E",
    "group": "admin",
    "path": "/admin/audit",
    "file": "(app)/admin/audit/page.tsx",
    "tier": "must",
    "roles": [
      "admin",
      "caseManager"
    ],
    "tests": [
      9
    ],
    "note": "Immutable, append-only, tamper-evident; every view/download/export (§7.2)."
  },
  {
    "id": "admin.consent",
    "title": "Consent records viewer",
    "section": "9E",
    "group": "admin",
    "path": "/admin/consent",
    "file": "(app)/admin/consent/page.tsx",
    "tier": "must",
    "roles": [
      "admin",
      "caseManager"
    ],
    "tests": [
      7,
      9
    ]
  },
  {
    "id": "admin.retention",
    "title": "Retention / erasure / DSAR management",
    "section": "9E",
    "group": "admin",
    "path": "/admin/retention",
    "file": "(app)/admin/retention/page.tsx",
    "tier": "must",
    "roles": [
      "admin"
    ]
  },
  {
    "id": "system.not-found",
    "title": "404 not found",
    "section": "9F",
    "group": "system",
    "path": "*",
    "file": "not-found.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "special": true,
    "note": "Next special file (not-found.tsx)."
  },
  {
    "id": "system.forbidden",
    "title": "403 access denied",
    "section": "9F",
    "group": "system",
    "path": "/403",
    "file": "(system)/403/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "system.error",
    "title": "500 / error",
    "section": "9F",
    "group": "system",
    "path": "*",
    "file": "error.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "special": true,
    "note": "Next special file (error.tsx, client component)."
  },
  {
    "id": "system.maintenance",
    "title": "Maintenance",
    "section": "9F",
    "group": "system",
    "path": "/maintenance",
    "file": "(system)/maintenance/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "system.session-expired",
    "title": "Session expired",
    "section": "9F",
    "group": "system",
    "path": "/session-expired",
    "file": "(system)/session-expired/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  },
  {
    "id": "system.case-access-expired",
    "title": "Case access expired (90-day inactivity)",
    "section": "9F",
    "group": "system",
    "path": "/case-access-expired",
    "file": "(system)/case-access-expired/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "note": "90-day receiving-clinician inactivity expiry (§5/§7.2)."
  },
  {
    "id": "system.offline",
    "title": "Offline (PWA shell)",
    "section": "9F",
    "group": "system",
    "path": "/offline",
    "file": "(system)/offline/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ],
    "note": "Static offline fallback also served from public/offline.html by the service worker."
  },
  {
    "id": "system.consent-expired",
    "title": "Consent expired notice",
    "section": "9F",
    "group": "system",
    "path": "/consent-expired",
    "file": "(system)/consent-expired/page.tsx",
    "tier": "must",
    "roles": [
      "public"
    ]
  }
];

export const ROUTES_BY_ID: Record<string, RouteMeta> = Object.fromEntries(
  ROUTES.map((route) => [route.id, route]),
);

export function getRoute(id: string): RouteMeta | undefined {
  return ROUTES_BY_ID[id];
}

export function routesByGroup(group: RouteGroup): RouteMeta[] {
  return ROUTES.filter((route) => route.group === group);
}
